version: "3.3"

services:

  firefox:
    image: jlesage/firefox
    container_name: firefox
    volumes:
      - ./firefox/config:/config:rw
    ports:
      - "5800:5800"
    restart: unless-stopped        
